# Generated by Django 3.0.4 on 2020-03-24 15:14
from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.db import migrations
import json
from django.contrib.gis.geos import fromstr, GEOSGeometry
from pathlib import Path

from shops.models import Shop, User


def seed(source, owner: User):
    with open(str(source)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name', 'no-name')
                    address = tags.get('addr:street', '')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = GEOSGeometry(f'POINT({longitude} {latitude})', srid=32140)

                    if name == 'no-name' or address == '':
                        continue

                    owner.shop_set.create(name=name, location=location, street_address=address)
            except KeyError:
                pass


def seed_shops(apps, schema_editor):
    try:
        owner = User.objects.filter(user_type=2)[:1].get()
    except User.DoesNotExist:
        owner = User(username='shop_owner', email='owner@shop.tes', password=make_password('testpassword'),
                     user_type=2)

        owner.save()

    json_file = Path(__file__).parents[2] / 'nigeria_shops.json'

    seed(json_file, owner)


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_shops)
    ]
