# Generated by Django 3.0.4 on 2020-03-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[{1, 'shop_user'}, {2, 'shop_owner'}, {3, 'admin'}], default=1),
        ),
    ]
