# Generated by Django 3.0.4 on 2020-03-24 21:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20200324_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=32140),
        ),
        migrations.AlterField(
            model_name='shop',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
